#!/bin/sh

host="localhost"
port="14609"
usage="Usage: $0 [-h host_address] [-p port_number|-f] filename"

while getopts "h:p:f" opt; do
  case "$opt" in
    h) host="$OPTARG" ;;
    p) port="$OPTARG" ;;
    f) port="" ;;
    \?) echo $usage >&2
      exit 1 ;;
  esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
  echo $usage >&2
  exit 1
fi
filename="$1"

if [ -z "$port" ]; then
  if [ -f .otojsd_port ]; then
    port="$(cat .otojsd_port)"
  else
    echo "Error: .otojsd_port file not found." >&2
    exit 1
  fi
fi

curl -X POST "http://${host}:${port}" --data-binary @"$filename"
